api_call:
  description: Test the api call, check the log for results
  fields:
    entry_id:
      name: Entity ID
      description: The OWM history instance
      required: true
      selector:
        config_entry:
          integration: openweathermaphistory

list_vars:
  description: list available variables, check the log for results
  fields:
    entry_id:
      name: Entity ID
      description: The OWM history instance
      required: true
      selector:
         config_entry:
            integration: openweathermaphistory

